# Generated by Django 5.2.17 on 2026-08-22 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('min_meaningful_loc', models.PositiveIntegerField(default=50000)),
                ('min_meaningful_commits', models.PositiveIntegerField(default=5)),
                ('min_meaningful_prs', models.PositiveIntegerField(default=4)),
                ('weight_repository', models.FloatField(default=20.0)),
                ('weight_git_history', models.FloatField(default=15.0)),
                ('weight_code_quality', models.FloatField(default=15.0)),
                ('weight_documentation', models.FloatField(default=10.0)),
                ('weight_testing', models.FloatField(default=10.0)),
                ('weight_security', models.FloatField(default=10.0)),
                ('weight_licensing_ip', models.FloatField(default=15.0)),
                ('weight_ownership', models.FloatField(default=5.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('repository', 'Repository Requirements'), ('git_history', 'Git History'), ('code_quality', 'Code Quality'), ('documentation', 'Documentation'), ('testing', 'Testing'), ('security', 'Security'), ('licensing', 'Licensing / IP'), ('ownership', 'Ownership')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.FloatField(default=0.0)),
                ('decision', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('conditionally_eligible', 'Conditionally Eligible'), ('requires_human_review', 'Requires Human Review'), ('insufficient_data', 'Insufficient Data')], default='insufficient_data', max_length=50)),
                ('passed_rules', models.PositiveIntegerField(default=0)),
                ('failed_rules', models.PositiveIntegerField(default=0)),
                ('warnings', models.PositiveIntegerField(default=0)),
                ('unknown_rules', models.PositiveIntegerField(default=0)),
                ('critical_findings', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='repositories.analysissnapshot')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='compliance.compliancepolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('not_applicable', 'Not Applicable'), ('unknown', 'Unknown')], max_length=20)),
                ('evidence', models.JSONField(default=dict)),
                ('remediation', models.TextField(blank=True)),
                ('is_critical_failure', models.BooleanField(default=False)),
                ('score_contribution', models.FloatField(default=0.0)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='compliance.complianceevaluation')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancerule')),
            ],
            options={
                'unique_together': {('evaluation', 'rule')},
            },
        ),
    ]
