# Generated by Django 5.2.17 on 2026-08-22 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('primary_language', models.CharField(max_length=50)),
                ('additional_languages', models.JSONField(blank=True, default=list)),
                ('project_type', models.CharField(choices=[('library', 'Library/Package'), ('framework', 'Framework'), ('application', 'Application'), ('service', 'Service/API'), ('tool', 'Developer Tool'), ('other', 'Other')], default='application', max_length=20)),
                ('current_version', models.CharField(blank=True, max_length=50)),
                ('development_status', models.CharField(choices=[('planning', 'Planning'), ('pre_alpha', 'Pre-Alpha'), ('alpha', 'Alpha'), ('beta', 'Beta'), ('production', 'Production/Stable'), ('maintenance', 'Maintenance')], default='planning', max_length=20)),
                ('repository_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('license_info', models.CharField(blank=True, max_length=100)),
                ('approximate_loc', models.PositiveIntegerField(default=0)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('last_development_date', models.DateField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('technical_review', 'Technical Review'), ('compliance_review', 'Compliance Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declaration_text', models.TextField(help_text='The exact text the user agreed to')),
                ('declaration_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('co_owner', 'Co-Owner'), ('developer', 'Developer'), ('maintainer', 'Maintainer'), ('reviewer', 'Reviewer')], default='developer', max_length=20)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('contribution_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('readme', 'README'), ('architecture', 'Architecture Document'), ('technical', 'Technical Documentation'), ('api', 'API Documentation'), ('installation', 'Installation Guide'), ('deployment', 'Deployment Guide'), ('dependency', 'Dependency Documentation'), ('testing', 'Testing Documentation'), ('ownership', 'Ownership Declaration File'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='project_docs/')),
                ('version', models.CharField(blank=True, default='1.0', max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('technical_review', 'Technical Review'), ('compliance_review', 'Compliance Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('to_state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('technical_review', 'Technical Review'), ('compliance_review', 'Compliance Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['state'], name='projects_pr_state_2693f7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_pr_categor_30f4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['primary_language'], name='projects_pr_primary_879834_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcontributor',
            unique_together={('project', 'user')},
        ),
    ]
