# Generated by Django 5.2.17 on 2026-08-22 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('feature_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=20)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('features', models.JSONField(default=dict)),
                ('extraction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vector', to='repositories.analysissnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('gradient_boosting', 'Gradient Boosting'), ('clustering', 'Clustering'), ('similarity', 'Similarity Engine'), ('heuristic', 'Rule-based Heuristic')], max_length=50)),
                ('feature_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('experiment', 'Experiment'), ('validated', 'Validated'), ('staging', 'Staging'), ('production', 'Production'), ('retired', 'Retired')], default='experiment', max_length=20)),
                ('model_artifacts', models.JSONField(default=dict)),
                ('training_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.dataset')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='intelligence.modelregistry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_label', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('explanation', models.JSONField(default=dict)),
                ('feature_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.featurevector')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='intelligence.modelregistry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.CharField(choices=[('correct', 'Prediction Correct'), ('incorrect', 'Prediction Incorrect'), ('needs_review', 'Needs Review')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='intelligence.prediction')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('split', models.CharField(choices=[('train', 'Train'), ('validation', 'Validation'), ('test', 'Test')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='intelligence.dataset')),
                ('feature_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.featurevector')),
            ],
            options={
                'unique_together': {('dataset', 'feature_vector')},
            },
        ),
    ]
