# Generated by Django 5.2.17 on 2026-08-22 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_commercial', models.BooleanField(default=False)),
                ('default_duration_days', models.IntegerField(default=365)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('under_negotiation', 'Under Negotiation'), ('licensed', 'Licensed'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('approved_review_case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reviews.reviewcase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_products', to='projects.project')),
                ('available_types', models.ManyToManyField(to='licensing.licensetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('negotiation', 'Negotiation'), ('terms_agreed', 'Terms Agreed'), ('agreement_pending', 'Agreement Pending'), ('signed', 'Signed'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=30)),
                ('intended_usage', models.TextField()),
                ('requested_duration_days', models.IntegerField(default=365)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='licensing.licenseproduct')),
                ('requested_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='licensing.licensetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed'), ('periodic', 'Periodic'), ('usage_based', 'Usage Based'), ('negotiated', 'Negotiated'), ('custom', 'Custom')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_commercial', models.BooleanField(default=False)),
                ('ai_training_permitted', models.BooleanField(default=False)),
                ('redistribution_permitted', models.BooleanField(default=False)),
                ('modification_permitted', models.BooleanField(default=False)),
                ('duration_days', models.IntegerField(default=365)),
                ('is_accepted', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_versions', to='licensing.licenserequest')),
            ],
            options={
                'unique_together': {('request', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('partially_signed', 'Partially Signed'), ('fully_signed', 'Fully Signed'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='licensing.licenserequest')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='licensing.licenseterms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='licensing.agreement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NegotiationProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_counter', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='licensing.licenserequest')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.licenseterms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('startup', 'Startup'), ('enterprise', 'Enterprise'), ('research_org', 'Research Organization'), ('university', 'University'), ('individual', 'Individual'), ('other', 'Other')], default='other', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='licensing.organization'),
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='licensing.agreement')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
