# Generated by Django 5.2.17 on 2026-08-22 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer_name', models.CharField(max_length=150, unique=True)),
                ('last_processed_timestamp', models.DateTimeField()),
                ('last_processed_event_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('quarter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_project_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('primary_language', models.CharField(max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchIndexLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index_name', models.CharField(max_length=100)),
                ('indexed_object_id', models.CharField(max_length=100)),
                ('index_version', models.CharField(max_length=50)),
                ('status', models.CharField(default='indexed', max_length=20)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=150)),
                ('event_version', models.CharField(default='v1', max_length=20)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('causation_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventProcessingError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer_name', models.CharField(max_length=150)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('dead_letter', 'Dead Letter'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_platform.domainevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required_fields', models.JSONField(default=list)),
                ('optional_fields', models.JSONField(default=list)),
                ('producer', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='draft', max_length=20)),
            ],
            options={
                'unique_together': {('event_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FactLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_type', models.CharField(max_length=50)),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_platform.dimdate')),
                ('event_reference', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_platform.domainevent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_platform.dimproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactRepositoryAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_duration_seconds', models.IntegerField(default=0)),
                ('approximate_loc', models.IntegerField(default=0)),
                ('is_successful', models.BooleanField(default=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_platform.dimdate')),
                ('event_reference', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_platform.domainevent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data_platform.dimproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['aggregate_type', 'aggregate_id'], name='data_platfo_aggrega_6b8254_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['event_type'], name='data_platfo_event_t_f89e74_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['timestamp'], name='data_platfo_timesta_4d2504_idx'),
        ),
    ]
