# Generated by Django 5.2.17 on 2026-08-22 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('projects', '0001_initial'),
        ('repositories', '0001_initial'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('triage', 'Triage'), ('technical_review', 'Technical Review'), ('ip_review', 'IP Review'), ('security_review', 'Security Review'), ('compliance_review', 'Compliance Review'), ('final_review', 'Final Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('remediation_required', 'Remediation Required')], default='draft', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('compliance_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='compliance.complianceevaluation')),
                ('previous_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_cases', to='reviews.reviewcase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cases', to='projects.project')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review_cases', to='repositories.analysissnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('triage', 'Triage'), ('technical_review', 'Technical Review'), ('ip_review', 'IP Review'), ('security_review', 'Security Review'), ('compliance_review', 'Compliance Review'), ('final_review', 'Final Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('remediation_required', 'Remediation Required')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('not_applicable', 'Not Applicable'), ('unknown', 'Unknown')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='reviews.reviewcase')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemediationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_action', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_remediations', to=settings.AUTH_USER_MODEL)),
                ('source_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.finding')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediations', to='reviews.reviewcase')),
                ('source_checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.reviewchecklistitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('triage', 'Triage'), ('technical_review', 'Technical Review'), ('ip_review', 'IP Review'), ('security_review', 'Security Review'), ('compliance_review', 'Compliance Review'), ('final_review', 'Final Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('remediation_required', 'Remediation Required')], max_length=30)),
                ('text', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.reviewcase')),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.reviewchecklistitem')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.finding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewTransitionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_state', models.CharField(max_length=30)),
                ('new_state', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='reviews.reviewcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('technical', 'Technical Reviewer'), ('ip', 'IP Reviewer'), ('security', 'Security Reviewer'), ('compliance', 'Compliance Reviewer'), ('final', 'Final Approver')], max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reviews.reviewcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('case', 'user', 'role')},
            },
        ),
    ]
