from django.contrib import admin
from django.urls import path, include
from core.views import home, dashboard, project_compliance, project_repository, project_security, project_reviews, reviewer_dashboard
import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('reviewer/', reviewer_dashboard, name='reviewer_dashboard'),
    path('project/<uuid:project_id>/compliance/', project_compliance, name='project_compliance'),
    path('project/<uuid:project_id>/repository/', project_repository, name='project_repository'),
    path('project/<uuid:project_id>/security/', project_security, name='project_security'),
    path('project/<uuid:project_id>/reviews/', project_reviews, name='project_reviews'),
    path('licensing/developer/', core.views.licensing_developer, name='licensing_developer'),
    path('licensing/licensee/', core.views.licensing_licensee, name='licensing_licensee'),
    path('licensing/admin/', core.views.licensing_admin, name='licensing_admin'),
    path('finance/developer/', core.views.finance_developer, name='finance_developer'),
    path('finance/admin/', core.views.finance_admin, name='finance_admin'),
    path('admin/platform/', core.views.admin_platform_dashboard, name='admin_platform_dashboard'),
    path('admin/operations/', core.views.admin_operations, name='admin_operations'),
    path('marketplace/', core.views.marketplace_home, name='marketplace_home'),
    path('marketplace/search/', core.views.marketplace_search, name='marketplace_search'),
    path('marketplace/project/<uuid:pk>/', core.views.marketplace_detail, name='marketplace_detail'),
    path('workspace/org/<uuid:org_id>/', core.views.org_workspace_dashboard, name='org_workspace'),
    path('workspace/project/<uuid:project_id>/', core.views.project_workspace_dashboard, name='project_workspace'),
    path('admin/intelligence/', core.views.admin_intelligence_dashboard, name='admin_intelligence'),
    path('admin/governance/<uuid:org_id>/', core.views.org_governance_dashboard, name='org_governance'),
    path('admin/data/', core.views.admin_data_dashboard, name='admin_data'),
    path('integrations/credentials/', core.views.api_credentials_view, name='api_credentials'),
    path('integrations/webhooks/', core.views.webhooks_view, name='webhooks'),
    path('api/v1/accounts/', include('accounts.urls', namespace='accounts')),
    path('api/v1/developers/', include('developers.urls', namespace='developers')),
    path('api/v1/projects/', include('projects.urls', namespace='projects')),
    path('api/v1/repositories/', include('repositories.urls', namespace='repositories')),
    path('api/v1/compliance/', include('compliance.urls', namespace='compliance')),
    path('api/v1/security/', include('security.urls', namespace='security')),
    path('api/v1/reviews/', include('reviews.urls', namespace='reviews')),
    path('api/v1/licensing/', include('licensing.urls', namespace='licensing')),
    path('api/v1/finance/', include('finance.urls', namespace='finance')),
    path('api/v1/marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('api/v1/collaboration/', include('collaboration.urls', namespace='collaboration')),
    path('api/v1/intelligence/', include('intelligence.urls', namespace='intelligence')),
    path('api/v1/governance/', include('governance.urls', namespace='governance')),
    path('api/v1/data_platform/', include('data_platform.urls', namespace='data_platform')),
    path('api/v1/analytics/', include('analytics.urls', namespace='analytics')),
    path('api/v1/integrations/', include('integrations.urls', namespace='integrations')),
    path('api/v1/notifications/', include('notifications.urls', namespace='notifications')),
]
