# Generated by Django 5.2.17 on 2026-08-22 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, help_text='Django-Q task ID', max_length=100)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commit_hash', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=50)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('total_loc', models.PositiveIntegerField(default=0)),
                ('meaningful_loc', models.PositiveIntegerField(default=0)),
                ('blank_lines', models.PositiveIntegerField(default=0)),
                ('comment_lines', models.PositiveIntegerField(default=0)),
                ('total_commits', models.PositiveIntegerField(default=0)),
                ('meaningful_commits', models.PositiveIntegerField(default=0)),
                ('total_authors', models.PositiveIntegerField(default=0)),
                ('first_commit_date', models.DateTimeField(blank=True, null=True)),
                ('latest_commit_date', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositories.analysisjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PullRequestStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=False)),
                ('total_prs', models.PositiveIntegerField(default=0)),
                ('open_prs', models.PositiveIntegerField(default=0)),
                ('merged_prs', models.PositiveIntegerField(default=0)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr_stats', to='repositories.analysissnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepositoryConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('generic', 'Generic Git'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], default='generic', max_length=20)),
                ('repo_url', models.URLField(help_text='Clone URL of the repository')),
                ('repo_name', models.CharField(blank=True, max_length=150)),
                ('default_branch', models.CharField(default='main', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending/Not Synced'), ('syncing', 'Syncing'), ('connected', 'Connected'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repository_connection', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analysissnapshot',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='repositories.repositoryconnection'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='repositories.repositoryconnection'),
        ),
        migrations.CreateModel(
            name='ClassificationStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('source', 'Source Code'), ('test', 'Tests'), ('doc', 'Documentation'), ('config', 'Configuration'), ('dependency', 'Dependencies/Vendor'), ('generated', 'Generated/Build'), ('binary', 'Binary/Asset'), ('unknown', 'Unknown')], max_length=20)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='repositories.analysissnapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'category')},
            },
        ),
        migrations.CreateModel(
            name='LanguageStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=50)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('loc', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='repositories.analysissnapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'language_name')},
            },
        ),
    ]
