# Generated by Django 5.2.17 on 2026-08-22 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('developer_type', models.CharField(choices=[('individual', 'Individual Developer'), ('company', 'Company / Startup'), ('student', 'Student'), ('hobbyist', 'Hobbyist'), ('other', 'Other')], default='individual', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of technical skills')),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of programming languages')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'developer profile',
                'verbose_name_plural': 'developer profiles',
            },
        ),
    ]
